server:
  address: ":8080"

api:
  timeout: 30s
  read_header_timeout: 5s

kafka:
  url: "localhost:9092"
  brokers:
    - "localhost:9092"
  topics:
    - "test_topic"
  group_id: "test-consumer-group"
  producer:
    ack_policy: 1
    retry_max: 5
  consumer:
    auto_commit_enable: false
    max_wait_time: 500ms

prometheus:
  host: "localhost:2112"

repository:
  hosts: "localhost:3306"
  dbname: "mysql"
  user: "mysql"
  password: "mysql"
  max_idle_conn: 5
  max_open_conn: 10
  max_idle_lifetime: 5m
  max_open_lifetime: 30m

tracing:
  endpoint: "http://localhost:4318"
  service_name: "hotels"
  enabled: true
