// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bookings": {
            "get": {
                "description": "Список бронирований",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "List hotel bookings",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Лимит (default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hotel.HotelBooking"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт бронирование номера (check_in, check_out в формате YYYY-MM-DD)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Create hotel booking",
                "parameters": [
                    {
                        "description": "Данные бронирования",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.createHotelBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/hotel.HotelBooking"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.errorResponse"
                        }
                    }
                }
            }
        },
        "/bookings/{id}": {
            "get": {
                "description": "Возвращает бронирование по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Get booking by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID бронирования (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hotel.HotelBooking"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет бронирование",
                "tags": [
                    "bookings"
                ],
                "summary": "Delete booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID бронирования (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.errorResponse"
                        }
                    }
                }
            }
        },
        "/dummy": {
            "get": {
                "description": "Возвращает 200 OK. Используется для проверки доступности сервиса.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "Dummy endpoint",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/hotels": {
            "get": {
                "description": "Список отелей с limit/offset",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hotels"
                ],
                "summary": "List hotels",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Лимит (default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hotel.Hotel"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_controller_v1.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт новый отель",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hotels"
                ],
                "summary": "Create hotel",
                "parameters": [
                    {
                        "description": "Данные отеля",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_controller_v1.createHotelRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/hotel.Hotel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_controller_v1.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_controller_v1.errorResponse"
                        }
                    }
                }
            }
        },
        "/hotels/{hotelId}/rooms": {
            "get": {
                "description": "Список номеров отеля",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "List hotel rooms",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID отеля",
                        "name": "hotelId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Лимит (default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hotel.HotelRoom"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт номер в указанном отеле",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Create hotel room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID отеля",
                        "name": "hotelId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные номера",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.createHotelRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/hotel.HotelRoom"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.errorResponse"
                        }
                    }
                }
            }
        },
        "/hotels/{id}": {
            "get": {
                "description": "Возвращает отель по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hotels"
                ],
                "summary": "Get hotel by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID отеля (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hotel.Hotel"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_controller_v1.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_controller_v1.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет отель. Сначала нужно удалить номера и бронирования.",
                "tags": [
                    "hotels"
                ],
                "summary": "Delete hotel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID отеля (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_controller_v1.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_controller_v1.errorResponse"
                        }
                    }
                }
            }
        },
        "/rooms/{id}": {
            "get": {
                "description": "Возвращает номер по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Get room by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID номера (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hotel.HotelRoom"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет номер. Сначала удалите бронирования этого номера.",
                "tags": [
                    "rooms"
                ],
                "summary": "Delete room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID номера (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.createHotelBookingRequest": {
            "type": "object",
            "properties": {
                "check_in": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "check_out": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "hotel_id": {
                    "type": "string"
                },
                "room_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.createHotelRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.createHotelRoomRequest": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "integer"
                },
                "room_type": {
                    "type": "string"
                },
                "rooms_available": {
                    "type": "integer"
                },
                "rooms_total": {
                    "type": "integer"
                }
            }
        },
        "github.com_SosisterRapStar_hotels_internal_adapter_controller_v1.errorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "hotel.Hotel": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "hotel.HotelBooking": {
            "type": "object",
            "properties": {
                "booking_id": {
                    "type": "string"
                },
                "check_in": {
                    "type": "string"
                },
                "check_out": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "hotel_id": {
                    "type": "string"
                },
                "room_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "hotel.HotelRoom": {
            "type": "object",
            "properties": {
                "hotel_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "room_type": {
                    "type": "string"
                },
                "rooms_available": {
                    "type": "integer"
                },
                "rooms_total": {
                    "type": "integer"
                }
            }
        },
        "internal_adapter_controller_v1.createHotelBookingRequest": {
            "type": "object",
            "properties": {
                "check_in": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "check_out": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "hotel_id": {
                    "type": "string"
                },
                "room_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_controller_v1.createHotelRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_controller_v1.createHotelRoomRequest": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "integer"
                },
                "room_type": {
                    "type": "string"
                },
                "rooms_available": {
                    "type": "integer"
                },
                "rooms_total": {
                    "type": "integer"
                }
            }
        },
        "internal_adapter_controller_v1.errorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Hotels API",
	Description:      "API сервиса отелей: бронирование номеров, участие в choreographic saga.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
